### ISSUE TITLE
CREATE FLIP ANIMATION

### ISSUE THREAD

**Issue by carreraprogrammer** [smunoz1988/frontendFlipCounter0622#1]
# FLIP COUNTER

In today's activity, we were able to take some advances with the flip animation counter. Every time that the counter change, we can change the background color. Instead of that, now we need to add a flip animation for the counter.

This is the code we added

` const unit = document.getElementById('top');
let countUnit = -1;
let countDecimal = 0;

const counter = () => {
    if (countUnit === 9) {
    countDecimal++;
    }
    countUnit++;
    if (countUnit === 10) {
        countUnit = 0;
    }
    if (countDecimal === 6) {
        countDecimal = 0;
    }
    unit.innerHTML = countUnit;
    var color = '#' + Math.floor(Math.random() * 16777215).toString(16);
    unit.style.color = color;
    if(countUnit % 2 === 0){
        unit.style.backgroundColor = 'red';
    } else {
        unit.style.backgroundColor = 'yellow';
    }
    // flipCard.setAttribute('data-content', randomContent); revisar con algo asi
};

counter();

setInterval(counter, 1000) `

@smunoz1988 and @fredo509, please post here any ideas, or if you find the solution

![giphy (1)](https://github.com/smunoz1988/frontendFlipCounter0622/assets/109081622/abec4842-2c28-4f4a-851c-b02c46825cf2)

**Comment by smunoz1988** [comment]
Thanks @carreraprogrammer and @fredo509 for your help!! 

Check for the solution I found.

**Comment by carreraprogrammer** [comment]
> Thanks @carreraprogrammer and @fredo509 for your help!! 
> 
> Check for the solution I found. 

Hello @smunoz1988, That is great 👏 now it's working? Did you pass the tests?
